version: "3"

services:
  db:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "car_sharing"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    restart: always
    volumes:
    - "db:/var/lib/postgresql/data"
    hostname: 'localhost'
    networks:
    - project
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"

  python:
    build:
      dockerfile: Dockerfile
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
#    command: bash -c "python manage.py makemigrations && python manage.py migrate &&
#      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
    - db
    volumes:
    - .:/app
    env_file:
    - dev.env
    networks:
    - project



volumes:
  db:

networks:
  project:
